spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://112.124.60.252:3306/smart_crm?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: ba257032dd3ea4f7


mybatis:
  mapper-locations: classpath:mybatis/*.xml
  #目的是为了省略resultType里的代码量
#  type-aliases-package: com.alibaba.demo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl